language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: N4wEHJF6xx+Z5L+mKYwZM/OCaL5IRnjU70uo/IWBhaRhS5sd2KB3qzhqZ4feh+wVM5PzNe5AaaCNkVxCZMNHJeFhxh8XMKfFKUVHgxxLD/fdl0YHv+Rs0L0rVV/r2gd7EdD7saa16i8Q57GgAErgDdr4SWRDO6wV0cGsJOL/Z/lQCnKhey38tBZDMI6lDLPt1dwGVhDjdK3KG2ZqvYHBivZcEoQ6PN0SkMjMILjlBrQelwWtr16D6400FXfsym8niNov7WoltpI5gFqOnU9livw89wk2CdQH1NerXZDXIfvSKBW8l77olFosd5mT7NArObqJaLsWV8s2NgwVYu2KltIA6RnBvft01S4TYQmlQOi9LYY0L7SraJSSUAJB/Vjg5GR9G+5kjdlSA+Fls7ht2BCFtuLyexsdX0o+WO24aQ8tYbmWUy636gwIm4CVq2RAmMcrCfjVT9r4NXVnRqxCKz966kdpsWH3BBfQfvNWJy4GyaPiWLLLmHiDo0Tg5CuUvz3x7I9iZ6Z3uekdCaQmgC8gBE5uxVt1OmHGbDunwIosm+s7YG/aocVUiLH95L/b6wHX1YM2Q/mQT1ftzuS4tNHy6wHnOp4KiPmVgpeUUELP9yBHZffoA/6zBrK1WhhEhSnIWJHkqGSocP3hoLelBwvyd7M23m+0wShH3AaIeb0=
  app: lr-titles-api-alpha
  on:
    repo: LandRegistry/titles-api
    branch: master
notifications:
  slack:
    secure: kcpD12Yl/uxCCwLXSGocpWUPu4FM1muzWMYFVaFh8xQe00zNzbTwizQc9dJHHezRPT4kQ+2Ql78IpRrG2aF6V2MBSB1dDAmEwIgWbvRAnLb/WEHJOyUXl/0u2/+BHO6b2OxUgZ/xfHLsfN0KYCZDo74MjNPMgnd5weiBHhTBC2HwOMIKIiMYSmCmHmfiVLjFk7YUkKMpW9ap3aZAiiaAk1sIVJ6Pb94KzAWdj6c9HWJCCxeNMUIcUaNFLPSH8JgbFhdDRuKoHYoykjug9CBM9UgYBrZ80DTksG0jovD+9PjoE//SYnSzDM5HBySKbTLfbcxB2Xtla4+FpPg78TFXvOdH/nEfUg3m6fHhJ0srZdZHxVr/FwrC3RT8gn8P3EHPB+BYBuD0g9wC9iq+4wMONcby35TxXRFAH9cK088EorqONwR6xKTWXJVk8FxDQgZ4ncq6lI4xIA1JExLHMEQA7+OKWRxSo2CiErOkILLJTlN/8nDGCJ6r+bqRthjuJJLUwQkof4h/vZvdvq6Mg3kCTWDWzffaKWYn9CdIBXDmDT3oPAR9Ze15h3IBAOU/TP+FaoTj9tFokFl+T8yADZ/hC6a/5K0m0AdHsUeAjbNlmsswWrsyoenX4Bm9eIupszhCQDOjGaOJyBPeyKe1mA5xwe6cLPznmkTUvi5rBZyUl8o=
